/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalTime;

/**
 *
 * @author Gamer
 */
public class PessoaGUI extends javax.swing.JFrame {

    private String nome;
    
    public PessoaGUI(String nome) {
        initComponents();
        this.nome = nome;
        saudacao();
    }
    
    public void saudacao(){
        
        Toolkit kit = Toolkit.getDefaultToolkit();  
        Dimension tamTela = kit.getScreenSize();  

        //Pega largura e altura da tela 
        double larg = (tamTela.width * 0.65);  
        double alt = (tamTela.height * 0.75);   
 
        setSize((int)larg,(int)alt);
        
        LocalTime horaAtual = LocalTime.now();
        
        LocalTime horaInicioDia = LocalTime.of(23,59,59);
        LocalTime horaMeioDia = LocalTime.of(11,59,59);
        LocalTime horaInicioNoite = LocalTime.of(17,59,59);
        if(horaAtual.isBefore(horaMeioDia)){
            lbSaudacao.setText("Bom dia,");
        } else if (horaAtual.isAfter(horaMeioDia) && horaAtual.isBefore(horaInicioNoite)){
            lbSaudacao.setText("Boa tarde,");
        } else if (horaAtual.isAfter(horaInicioNoite) && horaAtual.isBefore(horaInicioDia)){
            lbSaudacao.setText("Boa noite,");
        }
        
        lbNomeUsuario.setText(nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSaudacao = new javax.swing.JLabel();
        lbNomeUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btAdicionarReceita = new javax.swing.JButton();
        btRemoverReceita = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbReceitaMensal = new javax.swing.JLabel();
        lbDespesaMensal = new javax.swing.JLabel();
        lbValorReceitaMensal = new javax.swing.JLabel();
        lbValorDespesaMensal = new javax.swing.JLabel();
        btVisualizarRelatorioMensal = new javax.swing.JButton();
        btGerarRelatorioMensal = new javax.swing.JButton();
        btGravarRelatorioMensal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbReceitaMensal1 = new javax.swing.JLabel();
        lbValorReceitaMensal1 = new javax.swing.JLabel();
        btGerenciarConta = new javax.swing.JButton();
        lbReceitaMensal2 = new javax.swing.JLabel();
        lbValorReceitaMensal2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbReceitaMensal4 = new javax.swing.JLabel();
        lbReceitaMensal10 = new javax.swing.JLabel();
        btGerarDemReceitaAtual = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbReceitaMensal3 = new javax.swing.JLabel();
        lbReceitaMensal12 = new javax.swing.JLabel();
        btGerarDemDespesaAtual = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbReceitaMensal5 = new javax.swing.JLabel();
        lbValorReceitaMensal3 = new javax.swing.JLabel();
        lbReceitaMensal6 = new javax.swing.JLabel();
        lbValorReceitaMensal4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbReceitaMensal7 = new javax.swing.JLabel();
        lbReceitaMensal11 = new javax.swing.JLabel();
        btGerarDemReceitaFutura = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lbReceitaMensal8 = new javax.swing.JLabel();
        lbReceitaMensal13 = new javax.swing.JLabel();
        btGerarDemDespesaFutura = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btVisualizarRelatorioGeral = new javax.swing.JButton();
        btCarregarRelatorioGeral = new javax.swing.JButton();
        btGerarRelatoriaGeral = new javax.swing.JButton();
        lbReceitaMensal9 = new javax.swing.JLabel();
        lbValorReceitaMensal5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbSaudacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSaudacao.setText("...");

        lbNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNomeUsuario.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSaudacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomeUsuario)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btAdicionarReceita.setText("Adicionar Receita");
        btAdicionarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarReceitaActionPerformed(evt);
            }
        });

        btRemoverReceita.setText("Remover Receita");
        btRemoverReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(btAdicionarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btRemoverReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAdicionarReceita)
                        .addComponent(btRemoverReceita))
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbReceitaMensal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal.setText("Receita Mensal");

        lbDespesaMensal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDespesaMensal.setText("Despesa Mensal");

        lbValorReceitaMensal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbValorReceitaMensal.setText("R$...");

        lbValorDespesaMensal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbValorDespesaMensal.setText("R$...");

        btVisualizarRelatorioMensal.setText("Visualizar Relatório");

        btGerarRelatorioMensal.setText("Gerar Relatório");
        btGerarRelatorioMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatorioMensalActionPerformed(evt);
            }
        });

        btGravarRelatorioMensal.setText("CarregarRelatório");
        btGravarRelatorioMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarRelatorioMensalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVisualizarRelatorioMensal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbReceitaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDespesaMensal)
                            .addComponent(lbValorReceitaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbValorDespesaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btGerarRelatorioMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btGravarRelatorioMensal, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValorReceitaMensal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDespesaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValorDespesaMensal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVisualizarRelatorioMensal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGerarRelatorioMensal)
                    .addComponent(btGravarRelatorioMensal))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbReceitaMensal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal1.setText("Conta:");

        lbValorReceitaMensal1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbValorReceitaMensal1.setText("R$...");

        btGerenciarConta.setText("Gerenciar Conta");
        btGerenciarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarContaActionPerformed(evt);
            }
        });

        lbReceitaMensal2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal2.setText("Saldo atual");

        lbValorReceitaMensal2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbValorReceitaMensal2.setText("...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btGerenciarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValorReceitaMensal1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbReceitaMensal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbValorReceitaMensal2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbReceitaMensal2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValorReceitaMensal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReceitaMensal1)
                    .addComponent(lbValorReceitaMensal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGerenciarConta)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbReceitaMensal4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal4.setText("Receitas até o momento");

        lbReceitaMensal10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbReceitaMensal10.setText("R$...");

        btGerarDemReceitaAtual.setText("Gerar Demonstrativo");
        btGerarDemReceitaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarDemReceitaAtualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbReceitaMensal10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGerarDemReceitaAtual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal4)
                .addGap(36, 36, 36)
                .addComponent(lbReceitaMensal10)
                .addGap(18, 18, 18)
                .addComponent(btGerarDemReceitaAtual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbReceitaMensal3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal3.setText("Despesas até o momento");

        lbReceitaMensal12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbReceitaMensal12.setText("R$...");

        btGerarDemDespesaAtual.setText("Gerar Demonstrativo");
        btGerarDemDespesaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarDemDespesaAtualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbReceitaMensal12)
                    .addComponent(lbReceitaMensal3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(btGerarDemDespesaAtual)
                .addGap(81, 81, 81))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal3)
                .addGap(45, 45, 45)
                .addComponent(lbReceitaMensal12)
                .addGap(18, 18, 18)
                .addComponent(btGerarDemDespesaAtual)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbReceitaMensal5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal5.setText("Conta:");

        lbValorReceitaMensal3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbValorReceitaMensal3.setText("R$...");

        lbReceitaMensal6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal6.setText("Saldo futuro/geral");

        lbValorReceitaMensal4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbValorReceitaMensal4.setText("...");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbValorReceitaMensal3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbReceitaMensal5)
                    .addComponent(lbReceitaMensal6)
                    .addComponent(lbValorReceitaMensal4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValorReceitaMensal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lbReceitaMensal5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbValorReceitaMensal4)
                .addGap(11, 11, 11))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbReceitaMensal7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal7.setText("Receitas Futuras");

        lbReceitaMensal11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbReceitaMensal11.setText("R$...");

        btGerarDemReceitaFutura.setText("Gerar Demonstrativo");
        btGerarDemReceitaFutura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarDemReceitaFuturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbReceitaMensal11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGerarDemReceitaFutura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal7)
                .addGap(36, 36, 36)
                .addComponent(lbReceitaMensal11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGerarDemReceitaFutura)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbReceitaMensal8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal8.setText("Despesas futuras");

        lbReceitaMensal13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbReceitaMensal13.setText("R$...");

        btGerarDemDespesaFutura.setText("Gerar Demonstrativo");
        btGerarDemDespesaFutura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarDemDespesaFuturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbReceitaMensal13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(btGerarDemDespesaFutura)
                .addGap(91, 91, 91))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal8)
                .addGap(45, 45, 45)
                .addComponent(lbReceitaMensal13)
                .addGap(18, 18, 18)
                .addComponent(btGerarDemDespesaFutura)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btVisualizarRelatorioGeral.setText("Visualizar Relatório");

        btCarregarRelatorioGeral.setText("CarregarRelatório");
        btCarregarRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarRelatorioGeralActionPerformed(evt);
            }
        });

        btGerarRelatoriaGeral.setText("Gerar Relatório");
        btGerarRelatoriaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatoriaGeralActionPerformed(evt);
            }
        });

        lbReceitaMensal9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReceitaMensal9.setText("Listar Todos Lançamentos");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(lbReceitaMensal9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVisualizarRelatorioGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btGerarRelatoriaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCarregarRelatorioGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReceitaMensal9)
                .addGap(18, 18, 18)
                .addComponent(btVisualizarRelatorioGeral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGerarRelatoriaGeral)
                    .addComponent(btCarregarRelatorioGeral))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        lbValorReceitaMensal5.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        lbValorReceitaMensal5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorReceitaMensal5.setText("Powered by us");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValorReceitaMensal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbValorReceitaMensal5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerarRelatorioMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarRelatorioMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerarRelatorioMensalActionPerformed

    private void btGravarRelatorioMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarRelatorioMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGravarRelatorioMensalActionPerformed

    private void btGerenciarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerenciarContaActionPerformed

    private void btAdicionarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdicionarReceitaActionPerformed

    private void btRemoverReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemoverReceitaActionPerformed

    private void btGerarRelatoriaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarRelatoriaGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerarRelatoriaGeralActionPerformed

    private void btCarregarRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarRelatorioGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCarregarRelatorioGeralActionPerformed

    private void btGerarDemReceitaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarDemReceitaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerarDemReceitaAtualActionPerformed

    private void btGerarDemReceitaFuturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarDemReceitaFuturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerarDemReceitaFuturaActionPerformed

    private void btGerarDemDespesaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarDemDespesaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerarDemDespesaAtualActionPerformed

    private void btGerarDemDespesaFuturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarDemDespesaFuturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerarDemDespesaFuturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaGUI(args[0]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarReceita;
    private javax.swing.JButton btCarregarRelatorioGeral;
    private javax.swing.JButton btGerarDemDespesaAtual;
    private javax.swing.JButton btGerarDemDespesaFutura;
    private javax.swing.JButton btGerarDemReceitaAtual;
    private javax.swing.JButton btGerarDemReceitaFutura;
    private javax.swing.JButton btGerarRelatoriaGeral;
    private javax.swing.JButton btGerarRelatorioMensal;
    private javax.swing.JButton btGerenciarConta;
    private javax.swing.JButton btGravarRelatorioMensal;
    private javax.swing.JButton btRemoverReceita;
    private javax.swing.JButton btVisualizarRelatorioGeral;
    private javax.swing.JButton btVisualizarRelatorioMensal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbDespesaMensal;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbReceitaMensal;
    private javax.swing.JLabel lbReceitaMensal1;
    private javax.swing.JLabel lbReceitaMensal10;
    private javax.swing.JLabel lbReceitaMensal11;
    private javax.swing.JLabel lbReceitaMensal12;
    private javax.swing.JLabel lbReceitaMensal13;
    private javax.swing.JLabel lbReceitaMensal2;
    private javax.swing.JLabel lbReceitaMensal3;
    private javax.swing.JLabel lbReceitaMensal4;
    private javax.swing.JLabel lbReceitaMensal5;
    private javax.swing.JLabel lbReceitaMensal6;
    private javax.swing.JLabel lbReceitaMensal7;
    private javax.swing.JLabel lbReceitaMensal8;
    private javax.swing.JLabel lbReceitaMensal9;
    private javax.swing.JLabel lbSaudacao;
    private javax.swing.JLabel lbValorDespesaMensal;
    private javax.swing.JLabel lbValorReceitaMensal;
    private javax.swing.JLabel lbValorReceitaMensal1;
    private javax.swing.JLabel lbValorReceitaMensal2;
    private javax.swing.JLabel lbValorReceitaMensal3;
    private javax.swing.JLabel lbValorReceitaMensal4;
    private javax.swing.JLabel lbValorReceitaMensal5;
    // End of variables declaration//GEN-END:variables
}