/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.SwingUtilities;
import javax.swing.text.html.HTMLDocument;
import model.ContaBancaria;
import model.Pessoa;
import model.lancamentos.Receita;

/**
 *
 * @author Gamer
 */
public class VisDemonstrativoRecAtual extends javax.swing.JDialog {

    private Pessoa pessoaMostraDemAtual;

    /**
     * Creates new form VisDemonstrativoRecFutura
     */
    public VisDemonstrativoRecAtual(java.awt.Frame parent, boolean modal, Pessoa pessoa) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pessoaMostraDemAtual = pessoa;
        exibirDemonstrativoRecAtual();
    }

    public void exibirDemonstrativoRecAtual() {
        StringBuilder conteudo = new StringBuilder();
        List<Integer> idsReceitas = new ArrayList<>(pessoaMostraDemAtual.getReceitasMap().keySet());

// Ordene as chaves
        Collections.sort(idsReceitas);

// Itere sobre as chaves ordenadas
        for (Integer id : idsReceitas) {
            Receita rc = pessoaMostraDemAtual.getReceitasMap().get(id);
            conteudo.append("====================================\n");
            conteudo.append("ID: ").append(id).append("\n");
            conteudo.append("Data: ").append(rc.getDataLancamento()).append("\n");
            conteudo.append("Tipo: ").append(rc.getTipoReceita()).append("\n");
            conteudo.append("Valor: ").append(rc.getValor()).append("\n");
        }

        tArea.setText(conteudo.toString());
        tArea.setEditable(false);
        tArea.setCaretPosition(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Receitas Até o Momento");

        jScrollPane1.setName("spReceitasAtuais"); // NOI18N

        tArea.setEditable(false);
        tArea.setColumns(20);
        tArea.setRows(5);
        jScrollPane1.setViewportView(tArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // ... (Configuração do Look and Feel) ...

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pessoa pessoa;

                try {
                    pessoa = new Pessoa(args[0]);
                } catch (ArrayIndexOutOfBoundsException e) {
                    System.err.println("Erro: Argumentos de linha de comando insuficientes.");
                    return;
                }

                PessoaGUI pessoaGUI = new PessoaGUI(args[0], args[1]);
                pessoaGUI.setVisible(true);

                VisDemonstrativoRecAtual dialog = new VisDemonstrativoRecAtual(pessoaGUI, true, pessoa);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tArea;
    // End of variables declaration//GEN-END:variables
}
